services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YANDEX_TOKEN=${YANDEX_TOKEN}
      - ALLOWED_IDS=${ALLOWED_IDS}
      - PYTHONPATH=/usr/src
    restart: always
